query Report(
  $id: ID!
  $sort: CheckResultSortInput
  $filters: CheckResultFiltersInput
  $page: PageInput!
) {
  report(id: $id) {
    id
    checkResults(sort: $sort, page: $page, filters: $filters) {
      totalCount
      entries {
        url
        updatedAt
        responseCode
        redirectUrl
        size
        duration
        status
        errorReason
      }
    }
  }
}
