subscription ($id: ID!) {
  report(id: $id) {
    operation
    data {
      id
      processedCount
      totalCount
      status
      duration
      errorReason
      http1xxCount
      http2xxCount
      http3xxCount
      http4xxCount
      http5xxCount
    }
  }
}
