query ($host: ID!, $url: String!, $before: DateTime!) {
  website(host: $host) {
    host
    reports(
      filters: { url: { equals: $url }, updatedAt: { lt: $before } }
      sort: { by: updatedAt, order: desc }
      page: { current: 1, size: 1 }
    ) {
      entries {
        id
        totalCount
        http3xxCount
        http4xxCount
        http5xxCount
      }
    }
  }
}
