subscription {
  report {
    operation
    data {
      id
      createdAt
      http1xxCount
      http2xxCount
      http3xxCount
      http4xxCount
      http5xxCount
      totalCount
      processedCount
      status
      errorReason
      website {
        host
        faviconUrl
      }
    }
  }
}
