query (
  $host: ID!
  $sort: ReportSortInput!
  $page: Int!
  $filters: ReportFiltersInput
) {
  website(host: $host) {
    host
    reports(
      sort: $sort
      page: { current: $page, size: 20 }
      filters: $filters
    ) {
      totalCount
      entries {
        id
        createdAt
        http1xxCount
        http2xxCount
        http3xxCount
        http4xxCount
        http5xxCount
        totalCount
        processedCount
        status
        errorReason
      }
    }
  }
}
